### ISSUE TITLE
Is there a way to contact you regarding your sideprojects on Thunderstore?

### ISSUE THREAD

**Issue by derGrinch69** [1010101110/okcart#7]
Hi there!
I discovered one of your Projects on Thunderstore (Multiverse) and wanted to get in contact with you regarding this project.
Is there a way to talk to you about this project?

**Comment by 1010101110** [comment]
@derGrinch69 hey i just made https://github.com/1010101110/ValheimMods if you want to discuss stuff

also 1010101110#4526 discord

**Comment by derGrinch69** [comment]
Hi!
Sorry for filing this offtopic issue on that.
I presented your mod on r/ModdedValheim and someone posted some nice ideas regarding your mod and i just want to help him get in contact.
But i found you on nexus too and gave him the advice to post his request there.
Thank you for that quick response!

best regards
der_grinch_69
***@***.***

________________________________
Von: 1010101110 ***@***.***>
Gesendet: Samstag, 20. März 2021 23:25
An: 1010101110/okcart ***@***.***>
Cc: derGrinch69 ***@***.***>; Mention ***@***.***>
Betreff: Re: [1010101110/okcart] Is there a way to contact you regarding your sideprojects on Thunderstore? (#7)


@derGrinch69<https://github.com/derGrinch69> hey i just made https://github.com/1010101110/ValheimMods if you want to discuss stuff
